export { default as CommunitySupportedNumbers } from './CommunitySupportedNumbers'
export { default as FeaturedStarters } from './FeaturedStarters'
export { default as Footer } from './Footer'
export { default as GetStarted } from './GetStarted'
export { default as Hero } from './Hero'
export { default as Navigation } from './Navigation'
export { default as Features } from './Features'
export { default as LogosReferences } from './LogosReferences'
