import { Page } from 'components/templates'
import { ReactNode } from 'react'
import Image from 'next/image'
import FrameworkIcon from 'components/svgs/beta/FrameworkIcon'
import IDEIcon from 'components/svgs/beta/IDEIcon'
import CLIIcon from 'components/svgs/beta/CLIIcon'
import ResourcesIcon from 'components/svgs/beta/ResourcesIcon'
import CostIcon from 'components/svgs/beta/CostIcon'
import DeploymentIcon from 'components/svgs/beta/DeploymentIcon'
import ConsoleIcon from 'components/svgs/beta/ConsoleIcon'
import GithubIcon from 'components/svgs/beta/GithubIcon'
import InspectionIcon from 'components/svgs/beta/InspectionIcon'
import AWSIcon from 'components/svgs/beta/AWSIcon'
import CloudIcon from 'components/svgs/beta/CloudIcon'
import TeamIcon from 'components/svgs/beta/TeamIcon'
import { DISCORD_URL } from 'lib/constants'
import Link from 'next/link'
import { Scrollchor } from 'react-scrollchor'

interface Feature {
	icon: ReactNode
	title: string
	points: string[]
}

const UPCOMING_FEATURES: Array<Feature> = [
	{
		icon: <FrameworkIcon />,
		title: 'Batteries-included framework (shuttle-next)',
		points: [
			'First Rust framework with built-in features such as tracing, authentication, database management, user management, and i18n',
			'Compiles to WebAssembly (WASM) for improved speed, edge deploys, and advanced isolation',
			'Autogenerated OpenAPI documentation',
			'Interlinking of services to ensure static assurance for method existence and correct argument passing',
		],
	},
	{
		icon: <IDEIcon />,
		title: 'IDE Extension(s)',
		points: [
			'Deploy & observe your projects directly from your IDE',
			'Code snippets and resource helpers for improved development efficiency',
		],
	},
	{
		icon: <CLIIcon />,
		title: 'CLI Revamp',
		points: [
			'Elimination of proof-of-concept (POC) components, ensuring a stable and reliable experience',
			'Dead-easy project migration, just by running the   shuttlify   command',
		],
	},
	{
		icon: <ResourcesIcon />,
		title: 'More resources',
		points: [
			'Continuous updates & additions for the latest and greatest resources',
			'Simplifying the process of adding new resources to the framework',
			'Expand support for additional technologies such as SQLite, S3, EBS, and more',
		],
	},
	{
		icon: <FrameworkIcon />,
		title: 'Better frontend support',
		points: [
			'Establish first-class integration with Rust frontends, including Dioxus, Leptos, Yew, and Sycamore',
			'Enable Server-Side Rendering (SSR) capabilities for improved performance and user experience',
		],
	},
	{
		icon: <CostIcon />,
		title: 'Transparent cost',
		points: [
			'Implement itemized billing for project costs, providing detailed breakdown of expenses',
			'Cost prediction capabilities before event creating a new resource',
			'Suggestions on optimizing costs to help users make informed decisions.',
		],
	},
	{
		icon: <DeploymentIcon />,
		title: 'Multi-region deployments',
		points: ['Allow users to select the desired region for project deployment'],
	},
	{
		icon: <ConsoleIcon />,
		title: 'Console',
		points: [
			'Rollback functionality for easier project management and error recovery',
			'Insights into service limits and usage analytics to optimize resource utilization',
		],
	},
	{
		icon: <GithubIcon />,
		title: 'GitHub integration',
		points: ['Ephemeral previews of Pull Requests (PRs) to facilitate code review and testing'],
	},
	{
		icon: <InspectionIcon />,
		title: 'Better instrumentation inspection',
		points: [
			'Code instrumentation to measure and analyze execution time for improved performance optimization',
		],
	},
	{
		icon: <AWSIcon />,
		title: 'Use your own AWS account',
		points: ['Utilize your own AWS account, granting greater control and ownership'],
	},
	{
		icon: <CloudIcon />,
		title: 'Deploy to more cloud providers',
		points: ['Expand deployment options by adding support for additional cloud providers beyond AWS'],
	},
	{
		icon: <TeamIcon />,
		title: 'Team features/support',
		points: [
			'Introduce collaborative features and support for teams, fostering a collaborative development environment',
		],
	},
]

export default function Beta() {
	return (
		<section className='relative mx-auto w-full max-w-7xl'>
			<div className='group relative flex-grow overflow-hidden'>
				<div className='px-5 py-24 sm:px-10 lg:py-28'>
					<header>
						<h1 className='max-w-4xl font-gradual text-5xl font-bold text-[#C2C2C2] lg:text-6.5'>
							Shuttle lets you{' '}
							<span className='text-gradient bg-clip-text text-transparent'>
								build backends, fast.
							</span>
						</h1>
						<p className='mt-4 max-w-xl text-white dark:text-[#7A7A7A] sm:text-xl lg:text-2xl'>
							Today, we&apos;re moving into Beta.
						</p>
					</header>
				</div>
			</div>
			<div className='mx-auto flex w-full max-w-7xl flex-col gap-[100px] px-5 py-24 sm:px-10 lg:flex-row lg:py-28'>
				<div className='flex flex-1 flex-col gap-5 text-center text-[#7A7A7A] lg:text-left'>
					<h2 className='text-[20px]'>Shuttle officially entered Alpha back in March 2022.</h2>
					<p>
						In just a bit over a year, we’ve been fortunate to work with thousands of users and
						contributors in order to shape Shuttle as it is today.
					</p>
					<p>Now, we are entering beta.</p>
				</div>

				<div className='flex flex-1 flex-row justify-center gap-[60px] lg:flex-col'>
					<div className='flex flex-col'>
						<span className='text-[56px] font-bold text-[#C2C2C2] '>3,749</span>
						<p>Users</p>
					</div>
					<div className='flex flex-col'>
						<span className='text-[56px] font-bold text-[#C2C2C2] '>3000</span>
						<p>Community members</p>
					</div>
				</div>

				<div className='flex flex-1 flex-row justify-center gap-[60px] lg:flex-col'>
					<div className='flex flex-col'>
						<span className='text-[56px] font-bold text-[#C2C2C2] '>3,929</span>
						<p>Projects</p>
					</div>
					<div className='flex flex-col'>
						<span className='text-[56px] font-bold text-[#C2C2C2] '>65</span>
						<p>Contributors</p>
					</div>
				</div>

				<div className='flex flex-1 flex-row justify-center gap-[60px] lg:flex-col'>
					<div className='flex flex-col'>
						<span className='text-[56px] font-bold text-[#C2C2C2] '>4000</span>
						<p>GitHub stars</p>
					</div>
					<div className='flex flex-col'>
						<span className='text-[56px] font-bold text-[#C2C2C2] '>∞</span>
						<p>Minutes saved</p>
					</div>
				</div>
			</div>

			<div className='relative flex items-baseline justify-between gap-[80px]'>
				<div>
					<div className='max-w-3xl px-5 py-24 sm:px-10 lg:py-28'>
						<h1 className='mb-[30px] text-[56px] text-[#C2C2C2]' id='01'>
							01 What is Shuttle?
						</h1>

						<p className='mb-[30px]'>
							For those who may not be familiar, Shuttle is a cutting-edge, Rust-native cloud
							development platform that streamlines the development of code and manages
							infrastructure directly from your code.
						</p>
						<p className='mb-[30px]'>
							Our initial goal was simple: to provide the fastest possible backend development
							experience for the most beloved programming language out there - at least according to
							StackOverflow. We knew that the key to achieving this goal was to make getting started
							with Shuttle as fast and easy as possible, which is why we decided to focus on
							Infrastructue from Code.
						</p>
						<p className='mb-[30px]'>
							During our &quot;closed alpha&quot; phase, we experimented with a range of different
							approaches until we finally struck gold with the idea of using macros for resource
							provisioning. With this breakthrough, we were able to provide developers with
							everything they needed with just a single line of code.
						</p>
					</div>

					<div className='max-w-3xl px-5 py-24 sm:px-10 lg:py-28'>
						<h1 className='mb-[30px] text-[56px] text-[#C2C2C2]' id='02'>
							02 Why should I use it?
						</h1>
						<p className='mb-[30px]'>
							Navigating complex consoles and writing extensive YAML files for infrastructure
							configuration can be a time-consuming and error-prone process. These tasks often demand
							a steep learning curve and can detract from a developer&apos;s focus on core
							application logic. By utilizing infrastructure from code in a cloud development
							platform, we can address these challenges while building and deploying Rust backends.
						</p>
						<p className='mb-[30px]'>
							{' '}
							Rust, known for its safety, concurrency, and performance, is an excellent choice for
							creating efficient and reliable applications. Incorporating annotations into the main
							function allows you to leverage code generation and resource provisioning, streamlining
							your workflow and minimizing manual infrastructure management.
						</p>
						<p className='mb-[30px]'>
							This approach offers several benefits for various use cases, such as rapid prototyping
							and easy scaling of applications. Using Shuttle, you are simplifying the integration of
							development and operations processes, promoting collaboration and reducing the
							potential for errors since you are getting compile time insurance that you are getting
							the right infrastructure.
						</p>

						<div className='flex w-full justify-between'>
							<div className='flex flex-col gap-[14px]'>
								<h3 className='text-[24px] font-bold text-[#C2C2C2]'>AWS</h3>

								<p className='text-[20px] text-[#7A7A7A]'>3 Hours</p>
							</div>

							<div className='h-[83px] w-[1px] bg-[#463E3A]' />

							<div className='flex flex-col gap-[14px]'>
								<h3 className='text-[24px] font-bold text-[#C2C2C2]'>Pulumi</h3>

								<p className='text-[20px] text-[#7A7A7A]'>30 minutes</p>
							</div>

							<div className='h-[83px] w-[1px] bg-[#463E3A]' />

							<div className='flex flex-col gap-[14px]'>
								<h3 className='text-[24px] font-bold text-[#C2C2C2]'>Shuttle</h3>

								<p className='text-[20px] text-[#7A7A7A]'>7 minutes</p>
							</div>
						</div>
					</div>

					<div className='max-w-3xl px-5 py-24 sm:px-10 lg:py-28'>
						<h1 className='mb-[30px] text-[56px] text-[#C2C2C2]' id='03'>
							03 What’s coming in Beta?
						</h1>

						<h2 className='mb-4 text-[32px] text-[#D8D8D8]'>Stability</h2>

						<p className='mb-[30px]'>
							As we transition from the alpha phase to the beta release of Shuttle, addressing
							stability issues has been our top priority. We understand that our users need a
							reliable and seamless experience, especially when it comes to supporting
							production-level applications. Throughout the alpha phase, we listened to user feedback
							and identified areas that needed improvement, including fixing numerous papercuts and
							enhancing overall performance.
						</p>

						<p className='mb-[30px]'>
							With the beta release, we are proud to deliver the progress we&apos;ve made in ensuring
							a stable and dependable platform. Our team has worked tirelessly to address previous
							concerns and implement solutions that provide a solid foundation for developers. As we
							continue to evolve and refine Shuttle, we remain committed to maintaining and improving
							stability.
						</p>

						<h2 className='mb-4 text-[32px] text-[#D8D8D8]'>Reliability</h2>

						<p className='mb-[30px]'>
							Reliability is a cornerstone of any cloud development platform, as it ensures that
							users can depend on the platform&apos;s performance and trust its ability to support
							their applications.
						</p>

						<p className='mb-[30px]'>
							In response to valuable user feedback, we’ve made significant strides in improving the
							platform&apos;s reliability. To further strengthen this commitment and maintain
							transparency, we are excited to announce the release of a dedicated status page. This
							status page will provide real-time updates on the Shuttle&apos;s performance, uptime,
							and any ongoing maintenance or issues, allowing users to stay informed and make
							informed decisions about their development processes.
						</p>

						<p className='mb-[30px]'>The new status page is available here:</p>

						<Image
							src='/images/beta/status.png'
							alt='status page'
							width={784}
							height={500}
							className='mb-16'
						/>

						<h2 className='mb-4 text-[32px] text-[#D8D8D8]'>Console</h2>

						<p className='mb-[30px]'>
							Providing users with a variety of options to manage their projects and resources is
							essential. While the CLI has been powerful and easy-to-use, we learned that a certain
							portion of our users preferred a more visual and interactive approach.
						</p>

						<p className='mb-[30px]'>
							The console, designed with user experience at its core, offers a comprehensive and
							intuitive interface for managing projects, resources and configurations. It is supposed
							to complement the existing CLI, giving users the flexbility to choose the method that
							best suits their workflow and preferences.
						</p>

						<p className='mb-[30px]'>Don’t worry, the CLI isn’t going anywhere.</p>

						<Image
							src='/images/beta/console.png'
							alt='status page'
							width={784}
							height={500}
							className='mb-16'
						/>

						<h2 className='mb-4 text-[32px] text-[#D8D8D8]'>Support for Turso* & DynamoDB</h2>

						<p className='mb-[30px]'>
							The inclusion of Turso and DynamoDB support not only expands Shuttle&apos;s
							capabilities but also demonstrates a commitment to meeting the diverse needs of the
							development community. As Shuttle continues to grow and adapt, user feedback and the
							exploration of new technologies remain essential in shaping a versatile and reliable
							cloud development environment for developers to build, test, and deploy their
							applications with confidence.
						</p>

						<p className='mb-[30px]'>
							*Shuttle is currently limited to the eu-west-1 region so you won’t be able to utilize
							the benefits of edge databases but multi-region deployments are on our roadmap.
						</p>

						<h2 className='mb-4 text-[32px] text-[#D8D8D8]'>Better logs</h2>

						<p className='mb-[30px]'>
							Shuttle invested in improving the logging for the underlying platform and that’s what
							our users want for their services as well. We’ve rearchitected the way we collect logs
							at the level of the Shuttle control plane, but this is only the beginning. The
							community asked for richer and more customizable logging applicable to users’ services
							and we’re looking at a future where users will be able to own their logging pipelines
							while deploying on Shuttle.
						</p>
					</div>

					<div className='max-w-3xl px-5 py-24 sm:px-10 lg:py-28'>
						<h1 className='mb-[30px] text-[56px] text-[#C2C2C2]' id='04'>
							04 Billing
						</h1>

						<p className='mb-[30px]'>Some text missing.</p>
					</div>

					<div className='max-w-3xl px-5 py-24 sm:px-10 lg:py-28'>
						<h1 className='mb-[30px] text-[56px] text-[#C2C2C2]' id='05'>
							05 Launch week preview
						</h1>

						<p className='mb-[30px]'>
							As we head into beta, we&apos;ve prepared a lot of activities and events for you to
							engage with and make the most out of this exciting phase.
						</p>

						<Image src='/images/beta/preview.png' alt='status page' width={784} height={500} />
					</div>

					<div className='max-w-3xl px-5 py-24 sm:px-10 lg:py-28'>
						<h1 className='mb-[30px] text-[56px] text-[#C2C2C2]' id='06'>
							06 Testimonials
						</h1>

						<div className='mb-[30px] flex items-center gap-[30px]'>
							<div className='h-[100px] w-[3px] bg-[#333333]' />
							<div className='flex flex-col justify-center'>
								<p className='mb-2 italic'>
									“Deployed my second service with shuttle and I really like it! It&apos;s fast
									and integrates well with cargo, so I can focus on the Rust code instead of the
									deployment. Well done!”
								</p>
								<p>- Someone</p>
							</div>
						</div>

						<div className='mb-[30px] flex items-center gap-[30px]'>
							<div className='h-[100px] w-[3px] bg-[#333333]' />
							<div className='flex flex-col justify-center'>
								<p className='mb-2 italic'>
									“Deployed my second service with shuttle and I really like it! It&apos;s fast
									and integrates well with cargo, so I can focus on the Rust code instead of the
									deployment. Well done!”
								</p>
								<p>- Someone</p>
							</div>
						</div>

						<div className='flex items-center gap-[30px]'>
							<div className='h-[100px] w-[3px] bg-[#333333]' />
							<div className='flex flex-col justify-center'>
								<p className='mb-2 italic'>
									“Deployed my second service with shuttle and I really like it! It&apos;s fast
									and integrates well with cargo, so I can focus on the Rust code instead of the
									deployment. Well done!”
								</p>
								<p>- Someone</p>
							</div>
						</div>
					</div>

					<div className='max-w-3xl px-5 py-24 sm:px-10 lg:py-28'>
						<h1 className='mb-[30px] text-[56px] text-[#C2C2C2]' id='07'>
							07 What’s next
						</h1>

						<p className='mb-[30px]'>
							We won’t stop, we can’t stop. There are a lot of exciting things already lined up for
							the upcoming weeks & months and we are ecstatic to share them with you:
						</p>

						<div>
							{UPCOMING_FEATURES.map((feature, index) => (
								<div key={index} className='mb-[30px] flex gap-4'>
									<div className='flex h-[48px] w-[48px] items-center justify-center'>
										{feature.icon}
									</div>

									<div className='pt-2'>
										<h3 className='mb-4 text-[24px] font-bold text-[#D8D8D8]'>
											{feature.title}
										</h3>

										<ul className='list-disc'>
											{feature.points.map((point) => (
												<li key={point} className='ml-4'>
													{point}
												</li>
											))}
										</ul>
									</div>
								</div>
							))}
						</div>
					</div>

					<div className='max-w-3xl px-5 py-24 sm:px-10 lg:py-28'>
						<h1 className='mb-[30px] text-[56px] text-[#C2C2C2]' id='08'>
							08 Fundraising
						</h1>

						<p className='mb-[30px]'>Some text missing.</p>
					</div>

					<div className='max-w-3xl px-5 py-24 sm:px-10 lg:py-28'>
						<h1 className='mb-[30px] text-[56px] text-[#C2C2C2]' id='#09'>
							09 Growing our team
						</h1>

						<p className='mb-[30px]'>Some text missing.</p>
					</div>
				</div>
				<div className='sticky top-8 mr-8 hidden w-[280px] flex-col gap-3 rounded-[20px] border border-[#343E47] p-6 text-[#C2C2C2] sm:flex'>
					<p>
						<Scrollchor to='#01'>01 What is shuttle</Scrollchor>
					</p>
					<p>
						<Scrollchor to='#02'>02 Why should I use it</Scrollchor>
					</p>
					<p>
						<Scrollchor to='#03'>03 What’s coming in Beta?</Scrollchor>
					</p>
					<p>
						<Scrollchor to='#04'>04 Billing</Scrollchor>
					</p>
					<p>
						<Scrollchor to='#05'>05 Launch week preview</Scrollchor>
					</p>
					<p>
						<Scrollchor to='#06'>06 Testimonials</Scrollchor>
					</p>
					<p>
						<Scrollchor to='#07'>07 What’s next</Scrollchor>
					</p>
					<p>
						<Scrollchor to='#08'>08 Fundraising</Scrollchor>
					</p>
					<p>
						<Scrollchor to='#09'>09 Growing our team</Scrollchor>
					</p>
				</div>
			</div>
			<section className='relative mx-auto mb-20 mt-24 flex w-full max-w-3xl max-w-6xl flex-col items-center rounded-b-4xl px-5 pb-10 sm:px-10 md:mb-80 md:pb-48 lg:mt-28'>
				<Image
					src='/images/sections/batch/bg-batch.jpg'
					alt='background'
					fill
					className='absolute left-0 top-0 -z-10 hidden h-full w-full rounded-b-[32px] md:block'
				/>
				<h2 className='text-gradient mt-12 max-w-4xl bg-clip-text text-center font-gradual text-[56px] font-bold leading-[150%] text-[#C2C2C2]'>
					Start your journey now
				</h2>
				<p className='mt-8 max-w-2xl text-center text-xl text-[#7A7A7A]'>
					Shuttle - a serverless backend framework with the fastest build, test and deploy times ever.
				</p>

				<div className='mt-[58px] flex gap-2'>
					<button className='mt-4 h-[56px] w-full rounded-[14px] bg-[#D8D8D8] text-lg text-black sm:mt-0 sm:w-[154px]'>
						Try Shuttle
					</button>
					<Link href={DISCORD_URL}>
						<button className='button-shadow dark:border-gradient dark:shadow-gradient mt-4 h-[56px] w-full rounded-[14px] bg-[#000] bg-[#E9E9E9] text-lg text-[#C2C2C2] text-black hover:bg-gradient-to-r hover:from-[#fc540c] hover:to-[#f5c57a] hover:text-white dark:bg-black dark:text-[#C2C2C2] dark:hover:bg-none sm:mt-0 sm:w-[154px]'>
							Join Discord
						</button>
					</Link>
				</div>
			</section>
		</section>
	)
}

Beta.getLayout = (children: ReactNode) => <Page disableFooterMargin>{children}</Page>
