import { Page } from 'components/templates'
import { ReactNode } from 'react'
import Image from 'next/image'
import FrameworkIcon from 'components/svgs/beta/FrameworkIcon'
import IDEIcon from 'components/svgs/beta/IDEIcon'
import CLIIcon from 'components/svgs/beta/CLIIcon'
import ResourcesIcon from 'components/svgs/beta/ResourcesIcon'
import CostIcon from 'components/svgs/beta/CostIcon'
import DeploymentIcon from 'components/svgs/beta/DeploymentIcon'
import ConsoleIcon from 'components/svgs/beta/ConsoleIcon'
import GithubIcon from 'components/svgs/beta/GHIcon'
import InspectionIcon from 'components/svgs/beta/InspectionIcon'
import TeamIcon from 'components/svgs/beta/TeamIcon'
import { DISCORD_URL } from 'lib/constants'
import Link from 'next/link'
import { Scrollchor } from 'react-scrollchor'

interface Feature {
  icon: ReactNode
  title: string
  points: string[]
}

const UPCOMING_FEATURES: Array<Feature> = [
  {
    icon: <FrameworkIcon />,
    title: 'Batteries-included framework (shuttle-next)',
    points: [
      'First Rust framework with built-in features such as tracing, authentication, database management, user management, and i18n',
      'Compiles to WebAssembly (WASM) for improved speed, edge deploys, and advanced isolation',
      'Autogenerated OpenAPI documentation',
      'Interlinking of services to ensure static assurance for method existence and correct argument passing',
    ],
  },
  {
    icon: <IDEIcon />,
    title: 'IDE Extension(s)',
    points: [
      'Deploy & observe your projects directly from your IDE',
      'Code snippets and resource helpers for improved development efficiency',
    ],
  },
  {
    icon: <DeploymentIcon />,
    title: 'Improved logs',
    points: [
      'Richer and more customizable logging applicable to your services',
      'Ability to own your logging pipelines while deploying on Shuttle'
    ],
  },
  {
    icon: <CLIIcon />,
    title: 'LLM Features',
    points: [
      'Dead-easy project migration, just by running the shuttlify command',
      'Add features to your existing project via a single prompt',
      '-Optimising your infrastructure using smart suggestions'
    ],
  },
  {
    icon: <ResourcesIcon />,
    title: 'More resources',
    points: [
      'Continuous updates & additions for the latest and greatest resources',
      'Simplifying the process of adding new resources to the framework',
      'Expand support for additional technologies such as SQLite, S3, EBS, and more',
    ],
  },
  {
    icon: <FrameworkIcon />,
    title: 'Better frontend support',
    points: [
      'Establish first-class integration with Rust frontends, including Dioxus, Leptos, Yew, and Sycamore',
      'Enable Server-Side Rendering (SSR) capabilities for improved performance and user experience',
    ],
  },
  {
    icon: <CostIcon />,
    title: 'Transparent billing',
    points: [
      'Implement itemized billing for project costs, providing detailed breakdown of expenses',
      'Get cost estimates even before adding a resource',
      'Suggestions on optimizing costs to help users make informed decisions.',
    ],
  },
  {
    icon: <ConsoleIcon />,
    title: 'Console',
    points: [
      'Rollback functionality for easier project management and error recovery',
      'Insights into service limits and usage analytics to optimize resource utilization',
    ],
  },
  {
    icon: <GithubIcon />,
    title: 'GitHub integration',
    points: ['Previews of Pull Requests (PRs) to facilitate code review and testing'],
  },
  {
    icon: <InspectionIcon />,
    title: 'Flexibility',
    points: [
      'Allow the selection of the desired region for project deployment',
      'Utilize your own AWS account, granting greater control and ownership',
      'Expand deployment options by adding support for additional cloud providers beyond AWS'
    ],
  },
  {
    icon: <TeamIcon />,
    title: 'Team features/support',
    points: [
      'Introduce collaborative features and support for teams, fostering a collaborative development environment',
    ],
  },
]

export default function Beta() {
  return (
    <section className='relative mx-auto w-full max-w-7xl'>
      <div className='group relative flex-grow overflow-hidden'>
        <div className='px-5 py-24 sm:px-10 lg:py-28'>
          <header>
            <h1 className='max-w-4xl font-gradual text-5xl font-bold text-[#C2C2C2] lg:text-6.5'>
              Shuttle lets you{' '}
              <span className='text-gradient bg-clip-text text-transparent'>
                build backends, fast.
              </span>
            </h1>
            <p className='mt-4 max-w-xl text-white dark:text-[#7A7A7A] sm:text-xl lg:text-2xl'>
              Today, we&apos;re moving into Beta.
            </p>
          </header>
        </div>
      </div>
      <div className='mx-auto flex w-full max-w-7xl flex-col gap-[100px] px-5 py-24 sm:px-10 lg:flex-row lg:py-28'>
        <div className='flex flex-1 flex-col gap-5 text-center text-[#7A7A7A] lg:text-left'>
          <h2 className='text-[20px]'>Shuttle officially entered Alpha back in March 2022.</h2>
          <p>
            In just a bit over a year, we’ve been fortunate to work with thousands of users and
            contributors in order to shape Shuttle as it is today.
          </p>
          <p>Now, we are entering beta.</p>
        </div>

        <div className='flex flex-1 flex-col sm:flex-row justify-center gap-[60px] lg:flex-col items-center sm:items-start'>
          <div className='flex flex-col items-center sm:items-start'>
            <span className='text-[56px] font-bold text-[#C2C2C2]'>4,000+</span>
            <p>Users</p>
          </div>
          <div className='flex flex-col items-center sm:items-start'>
            <span className='text-[56px] font-bold text-[#C2C2C2] '>3,000</span>
            <p>Community members</p>
          </div>
        </div>

        <div className='flex flex-1 flex-col sm:flex-row justify-center gap-[60px] lg:flex-col items-center sm:items-start'>
          <div className='flex flex-col items-center sm:items-start'>
            <span className='text-[56px] font-bold text-[#C2C2C2] '>4,000+</span>
            <p>Projects</p>
          </div>
          <div className='flex flex-col items-center sm:items-start'>
            <span className='text-[56px] font-bold text-[#C2C2C2] '>68</span>
            <p>Contributors</p>
          </div>
        </div>

        <div className='flex flex-1 flex-col sm:flex-row justify-center gap-[60px] lg:flex-col items-center sm:items-start'>
          <div className='flex flex-col items-center sm:items-start'>
            <span className='text-[56px] font-bold text-[#C2C2C2] '>3,100+</span>
            <p>GitHub stars</p>
          </div>
          <div className='flex flex-col items-center sm:items-start'>
            <span className='text-[56px] font-bold text-[#C2C2C2] '>∞</span>
            <p>Minutes saved</p>
          </div>
        </div>
      </div>

      <div className='relative flex items-baseline justify-between gap-[80px]'>
        <div>
          <div className='max-w-3xl px-5 py-24 sm:px-10 lg:py-28'>
            <h1 className='mb-[30px] text-[56px] text-[#C2C2C2]' id='01'>
              01 What is Shuttle?
            </h1>

            <p className='mb-[30px]'>
              For those who may not be familiar, Shuttle is a cutting-edge, Rust-native cloud development platform that streamlines the development of code and manages infrastructure directly from your code.
            </p>
            <p className='mb-[30px]'>
              Our initial goal was simple: to provide the fastest possible backend development experience for the most beloved programming language out there - <Link href="https://survey.stackoverflow.co/2023/#technology-admired-and-desired" target="_blank" className='underline'>at least according to StackOverflow.</Link> We knew that the key to achieving this goal was to make getting started with Shuttle as fast and easy as possible, which is why we decided to focus on Infrastructure from Code.
            </p>

            <p className='mb-[30px]'>
              During our &quot;closed alpha&quot; phase, we experimented with a range of different
              approaches until we finally struck gold with the idea of using macros for resource
              provisioning. With this breakthrough, we were able to provide developers with
              everything they needed with just a single line of code.
            </p>

            <video className='w-full mb-[30px]' autoPlay loop>
              <source src='/videos/shuttle.mp4' type='video/mp4' />
            </video>
          </div>

          <div className='max-w-3xl px-5 py-24 sm:px-10 lg:py-28'>
            <h1 className='mb-[30px] text-[56px] text-[#C2C2C2]' id='02'>
              02 Why should I use it?
            </h1>
            <p className='mb-[30px]'>
              Navigating complex consoles and writing extensive YAML files for infrastructure configuration can be daunting, setting up and wiring all the infrastructure is a time-consuming and error-prone process. There is also a steep learning curve that can detract individuals and teams from focusing on core application logic. By utilizing Infrastructure from Code in a cloud development platform, we can address these challenges for the quickly growing community of Rust backend developers and teams.
            </p>
            <p className='mb-[30px]'>
              Rust, known for its safety, concurrency, and performance, is an excellent choice for creating efficient and reliable applications. Incorporating annotations into the main function allows you to leverage code generation and resource provisioning, streamlining your workflow and minimizing manual infrastructure management.
            </p>
            <p className='mb-[30px]'>
              This approach offers several benefits for various use cases, such as rapid prototyping and easy scaling of applications. Using Shuttle, you are simplifying the integration of development and operations processes, promoting collaboration and reducing the potential for errors since you are getting compile time insurance that you are getting the right infrastructure.
            </p>
          </div>

          <div className='max-w-3xl px-5 py-24 sm:px-10 lg:py-28'>
            <h1 className='mb-[30px] text-[56px] text-[#C2C2C2]' id='03'>
              03 What’s coming in Beta?
            </h1>

            <h2 className='mb-4 text-[32px] text-[#D8D8D8]'>Console</h2>

            <p className='mb-[30px]'>
              Providing users with a variety of options to manage their projects and resources is essential. While the CLI has been powerful and easy-to-use, we learned that a certain portion of our users preferred a more visual and interactive approach
            </p>

            <p className='mb-[30px]'>
              The console, designed with user experience at its core, offers a comprehensive and intuitive interface for managing projects, resources and configurations. It is supposed to complement the existing CLI, giving users the flexbility to choose the method that best suits their workflow and preferences.
            </p>

            <p className='mb-[30px]'>Don’t worry, the CLI isn’t going anywhere.</p>

            <Image
              src='/images/beta/console.gif'
              alt='shuttle console'
              width={784}
              height={500}
              className='mb-16'
            />

            <h2 className='mb-4 text-[32px] text-[#D8D8D8]'>Support for more resources</h2>

            <p className='mb-[30px]'>
              Continuous support for new resources is important for creating a flexible and dependable cloud development environment, especially in the ever-evolving Rust ecosystem. As part of this commitment, Shuttle now offers support for Turso and DynamoDB, expanding its capabilities.
            </p>

            <p className='mb-[30px]'>
              On top of that, we are introducing <i>community</i> examples. While we try to document as many frameworks/examples as possible, maintaining them can become difficult hence, with the help of our community, we are introducing examples that are curated, provided and maintained by our lovely community so that you can get up and running quickly.
            </p>

            <h2 className='mb-4 text-[32px] text-[#D8D8D8]'>Supercharging developer productivity with LLMs</h2>

            <p className='mb-[30px]'>
              We’ve revealed  <Link href="https://shuttle.rs/ai" target="_blank" className='underline'>Shuttle AI</Link> recently and we want to make it a companion in your development endeavors. The goal is simple, supercharging development productivity by enabling you to get started faster than ever. Even faster than getting a ‘hello-world’ app up and running.
            </p>
            <p className='mb-[30px]'>
              All it takes to generate & deploy a project is a single prompt, eg. <code>shuttle-ai build &quot;a blog backend&quot;</code> and in case you need an additional feature, for example, simply run eg. <code>shuttle-ai add-feature &quot;comments&quot;</code>.
            </p>

            <h2 className='mb-4 text-[32px] text-[#D8D8D8]'>Stability</h2>

            <p className='mb-[30px]'>
              As we transition from the alpha phase to the beta release of Shuttle, addressing stability issues has been our top priority. We understand that our users need a reliable and seamless experience, especially when it comes to supporting production-level applications. Throughout the alpha phase, we listened to user feedback and identified areas that needed improvement, including fixing papercuts and enhancing overall performance.
            </p>

            <p className='mb-[30px]'>
              With the beta release, we are proud to deliver the progress we&apos;ve made in ensuring a stable and dependable platform. Our team has worked tirelessly to address previous concerns and implement solutions that provide a solid foundation for developers. As we continue to evolve and refine Shuttle, we remain committed to maintaining and improving stability.
            </p>

            <h2 className='mb-4 text-[32px] text-[#D8D8D8]'>Reliability</h2>

            <p className='mb-[30px]'>
              Reliability is a cornerstone of any cloud development platform, as it ensures that users can depend on the platform&apos;s performance and trust its ability to support their applications.
            </p>

            <p className='mb-[30px]'>
              In response to valuable user feedback, we’ve significantly improved the platform&apos;s reliability. To further strengthen this commitment and maintain transparency, we are excited to announce the release of a dedicated status page. This status page will provide real-time updates on the Shuttle&apos;s performance, uptime, and any ongoing maintenance or issues, allowing users to stay informed and make informed decisions about their development processes.
            </p>

            <p className='mb-[30px]'>The new status page is available here: <Link href="https://status.shuttle.rs" className='underline'>status.shuttle.rs</Link> </p>

            <Image
              src='/images/beta/status.png'
              alt='status page'
              width={784}
              height={500}
              className='mb-16'
            />
          </div>

          <div className='max-w-3xl px-5 py-24 sm:px-10 lg:py-28'>
            <h1 className='mb-[30px] text-[56px] text-[#C2C2C2]' id='04'>
              04 Launch week preview
            </h1>

            <p className='mb-[30px]'>
              As we head into beta, we&apos;ve prepared a lot of activities and events for you to engage with and make the most out of this exciting phase.
            </p>

            <p className='mb-[30px]'>
              Tune into our <Link href="https://discord.gg/shuttle" target="_blank" className='underline'>Discord server</Link> to stay up-to-date as we progress through the launch week.
            </p>

            <Image src='/images/beta/preview.png' alt='status page' width={784} height={500} />
          </div>

          <div className='max-w-3xl px-5 py-24 sm:px-10 lg:py-28'>
            <h1 className='mb-[30px] text-[56px] text-[#C2C2C2]' id='05'>
              05 Testimonials
            </h1>

            <div className='mb-[30px] flex items-center gap-[30px]'>
              <div className='h-[100px] w-[3px] bg-[#333333]' />
              <div className='flex flex-col justify-center'>
                <p className='mb-2 italic'>
                  “Mind-blowing! What a huge addition to the Rust ecosystem! I&apos;m sure this will be a driveway to get more people into Rust.”
                </p>
                <p className='font-bold'>- Roberto Huertas, Software Engineer @ Datadog</p>
              </div>
            </div>

            <div className='mb-[30px] flex items-center gap-[30px]'>
              <div className='h-[100px] w-[3px] bg-[#333333]' />
              <div className='flex flex-col justify-center'>
                <p className='mb-2 italic'>
                  “Game changer, what a great project.”
                </p>
                <p className='font-bold'>- Dominykas, Staff Software Engineer @ Uber</p>
              </div>
            </div>

            <div className='mb-[30px] flex items-center gap-[30px]'>
              <div className='h-[100px] w-[3px] bg-[#333333]' />
              <div className='flex flex-col justify-center'>
                <p className='mb-2 italic'>
                  “You soon realize Shuttle is much more than just a host for your app. It&apos;s your Rust framework for the cloud; Infrastructure as Crates! This puts Shuttle in front of everything else I&apos;ve tried. I couldn&apos;t be more happy!”
                </p>
                <p className='font-bold'>- Owner oida.dev | Architect @ Dynatrace | Rust Linz</p>
              </div>
            </div>

            <div className='flex items-center gap-[30px]'>
              <div className='h-[100px] w-[3px] bg-[#333333]' />
              <div className='flex flex-col justify-center'>
                <p className='mb-2 italic'>
                  “The super easy deployment is what caught my eye, there&apos;s so many options for frontend deployment but not that many for backends. Feel to good to be true, almost!”
                </p>
                <p>- James, Full Stack Developer</p>
              </div>
            </div>
          </div>

          <div className='max-w-3xl px-5 py-24 sm:px-10 lg:py-28'>
            <h1 className='mb-[30px] text-[56px] text-[#C2C2C2]' id='06'>
              06 What’s next
            </h1>

            <p className='mb-[30px]'>
              We won’t stop, we can’t stop. There are a lot of exciting ideas we are eager to explore in the upcoming weeks & months and we are ecstatic to share them with you:
            </p>

            <div>
              {UPCOMING_FEATURES.map((feature, index) => (
                <div key={index} className='mb-[30px] flex gap-4'>
                  <div className='flex h-[48px] w-[48px] items-center justify-center'>
                    {feature.icon}
                  </div>

                  <div className='pt-2'>
                    <h3 className='mb-4 text-[24px] font-bold text-[#D8D8D8]'>
                      {feature.title}
                    </h3>

                    <ul className='list-disc'>
                      {feature.points.map((point) => (
                        <li key={point} className='ml-4'>
                          {point}
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>
              ))}
            </div>

            <p className='mb-[30px]'>
              We encourage you to submit your feedback, suggestions and feature requests through <Link href="https://github.com/shuttle-hq/shuttle/issues/new/choose" className='underline'>GitHub issues</Link>, as your input is invaluable in guiding the platform&apos;s growth and evolution.
            </p>

            <p className='mb-[30px] font-bold'>
              Together, we can create the fastest backend development experience ever.
            </p>
          </div>

          <div className='max-w-3xl px-5 py-24 sm:px-10 lg:py-28'>
            <h1 className='mb-[30px] text-[56px] text-[#C2C2C2]' id='07'>
              07 Fundraising
            </h1>

            <h2 className='mb-4 text-[32px] text-[#D8D8D8]'>Taking Shuttle to the Moon and Beyond!</h2>

            <p className='mb-[30px]'>
              As we are shifting gears from alpha to beta we’re excited to share that we’ve received a major boost from top-notch investors! Our journey has caught the attention of amazing partners at Y Combinator, HorizonVC, Abstraction Capital, and respected founders and product leaders from companies like Segment, ActionIQ, Sendbird, and DataDog.
            </p>

            <p className='mb-[30px]'>
              Their belief in Shuttle fuels our determination to redefine cloud development and we are extremely grateful that in addition to the amazing community supporting Shuttle, we are joined on this journey by some of the top investors and operators in the world.
            </p>

            <p className='mb-[30px]'>We’ll be sharing more details on this later on so stay tuned.</p>

            <Image
              src='/images/beta/investors.png'
              alt='status page'
              width={784}
              height={500}
              className='mb-16'
            />
          </div>

          <div className='max-w-3xl px-5 py-24 sm:px-10 lg:py-28'>
            <h1 className='mb-[30px] text-[56px] text-[#C2C2C2]' id='08'>
              08 Growing our team
            </h1>

            <p className='mb-[30px]'>
              Our core team is now 8 people spread across 6 countries and we are growing fast. It’s been very humbling to see the team expansion so far and this is just the beginning. As we continue to scale Shuttle, the team naturally keeps growing and we are over the moon with the way it’s shaping up.
            </p>

            <p className='mb-[30px]'>
              If you’re passionate about shaping the future of software development and want to join us in building the cloud platform of the future, check out our <Link href="https://www.shuttle.rs/about#careers" target="_blank" className='underline'> careers page</Link> and get in touch!
            </p>
          </div>
        </div>
        <div className='sticky top-8 mr-8 hidden w-[280px] flex-col gap-3 rounded-[20px] border border-[#343E47] p-6 text-[#C2C2C2] sm:flex'>
          <p>
            <Scrollchor to='#01'>01 What is shuttle</Scrollchor>
          </p>
          <p>
            <Scrollchor to='#02'>02 Why should I use it</Scrollchor>
          </p>
          <p>
            <Scrollchor to='#03'>03 What’s coming in Beta?</Scrollchor>
          </p>
          <p>
            <Scrollchor to='#04'>04 Launch week preview</Scrollchor>
          </p>
          <p>
            <Scrollchor to='#05'>05 Testimonials</Scrollchor>
          </p>
          <p>
            <Scrollchor to='#06'>06 What’s next</Scrollchor>
          </p>
          <p>
            <Scrollchor to='#07'>07 Fundraising</Scrollchor>
          </p>
          <p>
            <Scrollchor to='#08'>08 Growing our team</Scrollchor>
          </p>
        </div>
      </div>
      <section className='relative mx-auto mb-20 mt-24 flex w-full max-w-3xl max-w-6xl flex-col items-center rounded-b-4xl px-5 pb-10 sm:px-10 md:mb-80 md:pb-48 lg:mt-28'>
        <Image
          src='/images/sections/batch/bg-batch.jpg'
          alt='background'
          fill
          className='absolute left-0 top-0 -z-10 hidden h-full w-full rounded-b-[32px] md:block'
        />
        <h2 className='text-gradient mt-12 max-w-4xl bg-clip-text text-center font-gradual text-[56px] font-bold leading-[150%] text-[#C2C2C2]'>
          Start your journey now
        </h2>
        <p className='mt-8 max-w-2xl text-center text-xl text-[#7A7A7A]'>
          Shuttle - a serverless backend framework with the fastest build, test and deploy times ever.
        </p>

        <div className='mt-[58px] flex gap-2'>
          <button className='mt-4 h-[56px] w-full rounded-[14px] bg-[#D8D8D8] text-lg text-black sm:mt-0 sm:w-[154px]'>
            Try Shuttle
          </button>
          <Link href={DISCORD_URL}>
            <button className='button-shadow dark:border-gradient dark:shadow-gradient mt-4 h-[56px] w-full rounded-[14px] bg-[#000] bg-[#E9E9E9] text-lg text-[#C2C2C2] text-black hover:bg-gradient-to-r hover:from-[#fc540c] hover:to-[#f5c57a] hover:text-white dark:bg-black dark:text-[#C2C2C2] dark:hover:bg-none sm:mt-0 sm:w-[154px]'>
              Join Discord
            </button>
          </Link>
        </div>
      </section>
    </section >
  )
}

Beta.getLayout = (children: ReactNode) => <Page disableFooterMargin>{children}</Page>
